export const MIN_PASSWORD_LENGTH = 8;
export const MAX_PASSWORD_LENGTH = 24;
export const MIN_CHAT_MESSAGE_LENGTH = 1;
export const MAX_CHAT_MESSAGE_LENGTH = 50;
export const CREATE_MESSAGE_RATE_LIMIT_MS = 1000;